@base_url = http://localhost:3000/api/products

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RhbGJAdGVzdC5jb20iLCJpYXQiOjE1OTYxMjcxNDl9.KeyLtNLx6oUvwDtXLQBanEGzWtGa_R8o4RA8HbM_kac

###
// add a product
POST {{base_url}}/me HTTP/1.1
Content-Type: application/json
token: {{token}}

{
    "name": "apples",
    "image": "https://estaticos.miarevista.es/media/cache/1140x_thumb/uploads/images/gallery/59144d795cafe812663c986a/razonescomermanzana-int.jpg",
    "description": "añadiendo producto 2",    
    "price": 3,
    "location": "Las Palmas de GC"
}