@base_url = http://localhost:3000/api

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RhbGIyQHRlc3QuY29tIiwiaWF0IjoxNTk2NDIwNzM5LCJleHAiOjE1OTY0MjQzMzl9.MCEm8EiOYRaTPFq9zYE3J5k9pmakm-_NwftudSFNMZk
###
// create an account
POST {{base_url}}/auth/signup HTTP/1.1
Content-Type: application/json

{
    "user_username": "Alb2",
    "user_email": "testAlb2@test.com",
    "user_password": "123456"
}

###
// Login
POST {{base_url}}/auth/login HTTP/1.1
Content-Type: application/json

{
    "user_email": "testAlb2@test.com",
    "user_password": "123456"
}

###
GET {{base_url}}/auth/me HTTP/1.1
token: {{token}}
