@base_url = http://localhost:3000/api

@token  = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RhbGJAdGVzdC5jb20iLCJpYXQiOjE1OTcyMDM4MTgsImV4cCI6MTU5NzIwNzQxOH0.WfiDWEsNc0I1MctfMT33XTfmUa3U8kOiHlzTpQSEo9U
###
// create an account
POST {{base_url}}/auth/signup HTTP/1.1
Content-Type: application/json

{
    "user_username": "Alb2",
    "user_email": "testAlb2@test.com",
    "user_password": "123456"
}

###
// Login
POST {{base_url}}/auth/login HTTP/1.1
Content-Type: application/json

{
    "user_email": "testAlb@test.com",
    "user_password": "123456"
}

###
// whoami
GET {{base_url}}/auth/me HTTP/1.1
token:{{token}}


###
// view profile
GET {{base_url}}/users/me HTTP/1.1
token:{{token}}

###
/// add profile photo
PUT {{base_url}}/users/me
Content-Type: application/json
token:{{token}}

{
  "photo": "tu"
}

###
// add a favourite product
POST {{base_url}}/users/me/products HTTP/1.1
Content-Type: application/json
token: {{token}}

{
  "product": "5f321659c781566692a90c6f"
}
